### ISSUE TITLE
Better warnings on trying to use the network (from a poorly named job)

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2534]
Could be interesting - if you try to run a job that attempts to network, and networking has not explicitly been named as part of the job, is there a better way to warn users? as of now, you just get a wall of stderr.

```
      stderr: |-
        Traceback (most recent call last):
          File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
            conn = connection.create_connection(
          File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
            for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
          File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
            for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
        socket.gaierror: [Errno -3] Temporary failure in name resolution

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
            httplib_response = self._make_request(
          File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 415, in _make_request
            conn.request(method, url, **httplib_request_kw)
          File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
            super(HTTPConnection, self).request(method, url, body=body, headers=headers)
          File "/usr/lib/python3.10/http/client.py", line 1282, in request
            self._send_request(method, url, body, headers, encode_chunked)
          File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
            self.endheaders(body, encode_chunked=encode_chunked)
          File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
            self._send_output(message_body, encode_chunked=encode_chunked)
          File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
            self.send(msg)
          File "/usr/lib/python3.10/http/client.py", line 975, in send
            self.connect()
          File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
            conn = self._new_conn()
          File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
            raise NewConnectionError(
        urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fda88152

```

**Comment by wdbaruni** [comment]
Networking is now enabled by default. This shouldn't be an issue anymore
