### ISSUE TITLE
`bacalhau logs` panics (always?)

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2669]
```
% go run . logs --simon 
panic: unable to redefine 'h' shorthand in "logs" flagset: it's already used for "history" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0x140019bff00, 0x140019cd860)
        /Users/simon/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x354
github.com/spf13/pflag.(*FlagSet).VarPF(0x14001315b98?, {0x107425a80, 0x140018bdc6e}, {0x106372ea5, 0x4}, {0x106bf1de0, 0x1}, {0x140018bdc61, 0xd})
        /Users/simon/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x148
github.com/spf13/pflag.(*FlagSet).BoolVarP(0x106f649a0?, 0x1063a5306?, {0x106372ea5?, 0x1063a573e?}, {0x106bf1de0?, 0x1?}, 0x1?, {0x140018bdc61?, 0x0?})
        /Users/simon/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:55 +0x48
github.com/spf13/pflag.(*FlagSet).BoolP(...)
        /Users/simon/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:80
github.com/spf13/cobra.(*Command).InitDefaultHelpFlag(0x1?)
        /Users/simon/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1148 +0x10c
github.com/spf13/cobra.(*Command).execute(0x140019afb00, {0x1400196b490, 0x1, 0x1})
        /Users/simon/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:858 +0xb0
github.com/spf13/cobra.(*Command).ExecuteC(0x1400198fb00)
        /Users/simon/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/simon/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bacalhau-project/bacalhau/cmd/cli.Execute()
        /Users/simon/bacalhau/cmd/cli/root.go:196 +0x334
main.main()
        /Users/simon/bacalhau/main.go:37 +0x140
```

Something to do with it trying to automatically generate a help flag when the usage is printed.

**Comment by rossjones** [comment]
I'm looking at this as part of the other issue, I think it may have happened during the refactor
