### ISSUE TITLE
Node info publisher goes into loop and panics if cancelled at wrong moment

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#3484]
```
% bacalhau devstack
17:08:20.076 | INF pkg/repo/fs.go:81 > Initializing repo at '/var/folders/xz/qrd28pyx1095q2nzvhd9wb_c0000gn/T/2377010888' for environment 'production'
17:08:20.61 | INF pkg/devstack/devstack.go:95 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":3,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":0,"MemoryProfilingFile":"","NetworkType":"","NodeInfoPublisherInterval":"{30s 10ms 5s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":1}]
^C17:08:23.185 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.225 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.235 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.245 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.285 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.295 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.305 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.315 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.325 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.335 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.345 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.355 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.365 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.395 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.415 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.465 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.495 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.515 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.555 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.565 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.575 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.585 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.595 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.615 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.645 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.665 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.685 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.695 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.715 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.734 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.744 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.755 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.765 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.774 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.784 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.804 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.854 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.874 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.884 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.895 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.904 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.915 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.925 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.935 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.944 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.954 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.964 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.975 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.984 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:23.994 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.004 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.014 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.024 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.034 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.044 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.054 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.064 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.074 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.084 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.094 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.104 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.114 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.124 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.134 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.144 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.154 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.164 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.174 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.184 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.194 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.204 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.214 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.224 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.234 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.244 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.254 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.264 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.274 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.284 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.294 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.304 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.314 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.324 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.334 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.344 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.354 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.364 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.373 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.384 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.394 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.404 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.414 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.424 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.434 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.444 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.454 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.464 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.474 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.484 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.494 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.504 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.514 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.524 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.534 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.544 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.554 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.564 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.574 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.584 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.594 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.604 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.614 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.624 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.634 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.644 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.654 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.664 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.674 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.684 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.694 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.704 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.714 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.724 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.734 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.744 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.754 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.764 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.774 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.784 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.794 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.804 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.814 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.824 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.834 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.844 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.854 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.864 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.874 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.884 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.894 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.904 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.914 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.924 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.934 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.944 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.954 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.964 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.974 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.984 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:24.994 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.004 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.014 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.024 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
^C17:08:25.034 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.044 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.054 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.064 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.074 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.084 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.094 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.104 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.114 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.124 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.134 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.144 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.154 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.164 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.174 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.184 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.194 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.204 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.214 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.224 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.234 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.244 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.254 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.264 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.274 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.284 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.294 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.304 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.314 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.324 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.334 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.344 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.354 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.364 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.374 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.384 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.394 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.404 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.414 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.424 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.434 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.444 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.454 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.464 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.474 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.484 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.494 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.504 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.514 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.524 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.534 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.544 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.554 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.564 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.574 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.584 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.594 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.604 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.614 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.624 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.634 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.644 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.654 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.664 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.674 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.684 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.694 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.704 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.714 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
^C17:08:25.724 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.734 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.744 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.754 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.764 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.774 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.784 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.794 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.804 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.814 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.824 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.834 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.844 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.854 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.864 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.874 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.884 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
17:08:25.893 | ERR pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"
^C^Cpanic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/bacalhau-project/bacalhau/pkg/devstack.Setup({0x107d686a0, 0x140004aa480}, 0x140004aa390, 0x140007d1c70, {0x140007c8460, 0x12, 0x0?})
	github.com/bacalhau-project/bacalhau/pkg/devstack/devstack.go:141 +0x1644
github.com/bacalhau-project/bacalhau/cmd/cli/devstack.runDevstack(0x14000029800, 0x14000031f00, 0x0)
	github.com/bacalhau-project/bacalhau/cmd/cli/devstack/devstack.go:235 +0xaec
github.com/bacalhau-project/bacalhau/cmd/cli/devstack.NewCmd.func2(0x14000029800?, {0x106925992?, 0x0?, 0x0?})
	github.com/bacalhau-project/bacalhau/cmd/cli/devstack/devstack.go:89 +0x2c
github.com/spf13/cobra.(*Command).execute(0x14000029800, {0x109b0c980, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0x7cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1400064f800)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x380
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/bacalhau-project/bacalhau/cmd/cli.Execute({0x107d6b068?, 0x140003e3480})
	github.com/bacalhau-project/bacalhau/cmd/cli/root.go:187 +0x104
main.main()
	github.com/bacalhau-project/bacalhau/main.go:88 +0x12c
```

**Comment by rossjones** [comment]
The stack trace above contains two errors, both ther node_info_publisher problem, and the `index out of range [0] with length 0` which is coming from IPFS.  Both are resolved in https://github.com/bacalhau-project/bacalhau/pull/3487
