### ISSUE TITLE
'Error downloading job: server misbehaving / EOF' occurs when trying to download job results from demo network

### ISSUE THREAD

**Issue by AlekseyKorzik** [bacalhau-project/bacalhau#3562]
**Environment**: Lubuntu and Ubuntu VMs
Both client and server versions are 1.2.2

For any kind of job I tried following errors occur:
for the first attempt
`error downloading job: Get "http://public:6001/e-864db7fc-4afd-40c0-bca7-3dd5bdd64c7e.tgz": dial tcp: lookup public on 127.0.0.53:53: server misbehaving`
for any subsequent:
`error downloading job: EOF`

here is complete console output:
```
bacalhau docker run alpine echo hello
Using default tag: latest. Please specify a tag/digest for better reproducibility.
Job successfully submitted. Job ID: f073e8cc-2dca-4ae0-b921-76ab65b5d308
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

        Communicating with the network  ................  done ✅  0.2s
           Creating job for submission  ................  done ✅  0.0s
                       Job in progress  ................  done ✅  0.7s

To download the results, execute:
        bacalhau get f073e8cc-2dca-4ae0-b921-76ab65b5d308

To get more details about the run, execute:
        bacalhau describe f073e8cc-2dca-4ae0-b921-76ab65b5d308

bacalhau get f073e8cc-2dca-4ae0-b921-76ab65b5d308
Fetching results of job 'f073e8cc-2dca-4ae0-b921-76ab65b5d308'...
error downloading job: Get "http://public:6001/e-d1d62978-5aad-4714-884c-30a51660cf51.tgz": dial tcp: lookup public on 127.0.0.53:53: server misbehaving

bacalhau get f073e8cc-2dca-4ae0-b921-76ab65b5d308
Fetching results of job 'f073e8cc-2dca-4ae0-b921-76ab65b5d308'...
error downloading job: EOF

bacalhau logs f073e8cc-2dca-4ae0-b921-76ab65b5d308
panic: interface conversion: client.Client is *client.AuthenticatingClient, not *client.httpClient

goroutine 15 [running]:
github.com/bacalhau-project/bacalhau/pkg/publicapi/client/v2.(*Jobs).Logs(0xc000f2dd40?, {0x4017dc0?, 0xc000655bf0?}, 0x0?)
        github.com/bacalhau-project/bacalhau/pkg/publicapi/client/v2/api_jobs.go:83 +0xc5
github.com/bacalhau-project/bacalhau/cmd/util.Logs(0xc000e6d500, {{0x7ffc5db0c38f, 0x24}, {0x0, 0x0}, 0x0, 0x0})
        github.com/bacalhau-project/bacalhau/cmd/util/logging.go:39 +0x1aa
github.com/bacalhau-project/bacalhau/cmd/cli/job.NewLogCmd.func1(0xc000e6d500?, {0xc000eb68d0?, 0x1?, 0x1?})
        github.com/bacalhau-project/bacalhau/cmd/cli/job/logs.go:49 +0x8c
github.com/spf13/cobra.(*Command).execute(0xc000e6d500, {0xc000eb68a0, 0x1, 0x1})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0xc000971b00)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/bacalhau-project/bacalhau/cmd/cli.Execute({0x401a7f8?, 0xc000a13e00})
        github.com/bacalhau-project/bacalhau/cmd/cli/root.go:187 +0x108
main.main.func2()
        github.com/bacalhau-project/bacalhau/main.go:90 +0x33
created by main.main
        github.com/bacalhau-project/bacalhau/main.go:89 +0x1f8
```

Tried adding `--log-mode` flag with all available options but it does not output any additional information.

**Comment by rossjones** [comment]
There's a fix for this in https://github.com/bacalhau-project/bacalhau/pull/3555
A short-term fix is to specify the IPFS publisher (-p ipfs) when submitting the job, but this should be fixed in 1.2.3
