### ISSUE TITLE
unexpected fault address 0x0

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#486]
ETA: 2022Q4

```
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x16e74f7]

goroutine 6120242 [running]:
runtime.throw({0x2566f9b, 0xc0f45adf40})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc12681c998 sp=0xc12681c968 pc=0xd816d1
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:742 +0x2f6 fp=0xc12681c9e8 sp=0xc12681c998 pc=0xd97f16
github.com/libp2p/go-libp2p-core/peer.AddrInfo.MarshalJSON({{0xc1f0581e00, 0x22}, {0xc06278d0b0, 0x2, 0x1}})
        /home/luke/gocode/pkg/mod/github.com/libp2p/go-libp2p-core@v0.15.1/peer/addrinfo_serde.go:21 +0x1d7 fp=0xc12681ca80 sp=0xc12681c9e8 pc=0x16e74f7
github.com/libp2p/go-libp2p-core/peer.(*AddrInfo).MarshalJSON(0xc0a6e0e4e0)
        <autogenerated>:1 +0x5f fp=0xc12681cae0 sp=0xc12681ca80 pc=0x16ea9ff
encoding/json.marshalerEncoder(0xc1f4306500, {0x23304a0, 0xc14d85ce40, 0xd4cec9}, {0x50, 0xaa})
        /usr/local/go/src/encoding/json/encode.go:479 +0xbe fp=0xc12681cb68 sp=0xc12681cae0 pc=0xe8cf1e
encoding/json.arrayEncoder.encode({0x0}, 0xc1f4306500, {0x21b27a0, 0xc111270048, 0xd4cc92}, {0x28, 0xcc})
        /usr/local/go/src/encoding/json/encode.go:916 +0xb5 fp=0xc12681cbd8 sp=0xc12681cb68 pc=0xe90355
encoding/json.arrayEncoder.encode-fm(0x23, {0x21b27a0, 0xc111270048, 0xd58e50}, {0x28, 0x0})
        /usr/local/go/src/encoding/json/encode.go:909 +0x45 fp=0xc12681cc18 sp=0xc12681cbd8 pc=0xe99965
encoding/json.sliceEncoder.encode({0x21ed8e0}, 0xc1f4306500, {0x21b27a0, 0xc111270048, 0x21b27a0}, {0x0, 0x0})
        /usr/local/go/src/encoding/json/encode.go:889 +0x2e6 fp=0xc12681cd20 sp=0xc12681cc18 pc=0xe8fe86
encoding/json.sliceEncoder.encode-fm(0x21b27a0, {0x21b27a0, 0xc111270048, 0xe25a09}, {0x4, 0x0})
        /usr/local/go/src/encoding/json/encode.go:869 +0x45 fp=0xc12681cd60 sp=0xc12681cd20 pc=0xe998a5
encoding/json.(*encodeState).reflectValue(0x2251400, {0x21b27a0, 0xc111270048, 0xc0adaeaa50}, {0x60, 0x0})
        /usr/local/go/src/encoding/json/encode.go:360 +0x78 fp=0xc12681cdc0 sp=0xc12681cd60 pc=0xe8c5b8
encoding/json.interfaceEncoder(0xc1f4306500, {0x2251400, 0xc063db5260, 0x101}, {0xc9, 0xce})
        /usr/local/go/src/encoding/json/encode.go:716 +0xc8 fp=0xc12681ce08 sp=0xc12681cdc0 pc=0xe8e668
encoding/json.mapEncoder.encode({0x0}, 0xc1f4306500, {0x228ea00, 0xc0adaeaa20, 0x228ea00}, {0x2, 0x0})
        /usr/local/go/src/encoding/json/encode.go:814 +0x5c3 fp=0xc12681cfc8 sp=0xc12681ce08 pc=0xe8f283
encoding/json.mapEncoder.encode-fm(0x228ea00, {0x228ea00, 0xc0adaeaa20, 0x20302b}, {0x0, 0x0})
        /usr/local/go/src/encoding/json/encode.go:779 +0x45 fp=0xc12681d008 sp=0xc12681cfc8 pc=0xe997e5
encoding/json.(*encodeState).reflectValue(0xc12681d0a0, {0x228ea00, 0xc0adaeaa20, 0x7f9539c852b0}, {0x20, 0x89})
        /usr/local/go/src/encoding/json/encode.go:360 +0x78 fp=0xc12681d068 sp=0xc12681d008 pc=0xe8c5b8
encoding/json.(*encodeState).marshal(0x18, {0x228ea00, 0xc0adaeaa20}, {0x0, 0x0})
        /usr/local/go/src/encoding/json/encode.go:332 +0xfa fp=0xc12681d0e0 sp=0xc12681d068 pc=0xe8c1da
encoding/json.Marshal({0x228ea00, 0xc0adaeaa20})
        /usr/local/go/src/encoding/json/encode.go:161 +0x45 fp=0xc12681d140 sp=0xc12681d0e0 pc=0xe8b845
github.com/libp2p/go-libp2p-core/routing.(*QueryEvent).MarshalJSON(0xc0ee9d04c0)
        /home/luke/gocode/pkg/mod/github.com/libp2p/go-libp2p-core@v0.15.1/routing/query_serde.go:10 +0x1da fp=0xc12681d1a0 sp=0xc12681d140 pc=0x16fef5a
encoding/json.marshalerEncoder(0xc1e1e75000, {0x22b11a0, 0xc0ee9d04c0, 0xc12681d270}, {0xd6, 0x3c})
        /usr/local/go/src/encoding/json/encode.go:479 +0xbe fp=0xc12681d228 sp=0xc12681d1a0 pc=0xe8cf1e
encoding/json.(*encodeState).reflectValue(0xc12681d2c0, {0x22b11a0, 0xc0ee9d04c0, 0xc1f4306500}, {0x20, 0x89})
        /usr/local/go/src/encoding/json/encode.go:360 +0x78 fp=0xc12681d288 sp=0xc12681d228 pc=0xe8c5b8
encoding/json.(*encodeState).marshal(0xd544cd, {0x22b11a0, 0xc0ee9d04c0}, {0x0, 0x7b})
        /usr/local/go/src/encoding/json/encode.go:332 +0xfa fp=0xc12681d300 sp=0xc12681d288 pc=0xe8c1da
encoding/json.(*Encoder).Encode(0xc18dc0cf50, {0x22b11a0, 0xc0ee9d04c0})
        /usr/local/go/src/encoding/json/stream.go:206 +0x7e fp=0xc12681d380 sp=0xc12681d300 pc=0xe9817e
github.com/ipfs/go-ipfs-cmds/http.(*responseEmitter).Emit(0xc09f06e310, {0x22b11a0, 0xc0ee9d04c0})
        /home/luke/gocode/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.8.1/http/responseemitter.go:135 +0x385 fp=0xc12681d450 sp=0xc12681d380 pc=0x170dfc5
github.com/ipfs/go-ipfs/core/commands.glob..func52(0xc09f06e2a0, {0x2b56388, 0xc09f06e310}, {0x2395140, 0xc0264a7c70})
        /home/luke/gocode/pkg/mod/github.com/ipfs/go-ipfs@v0.13.1/core/commands/dht.go:192 +0x2ca fp=0xc12681d4e0 sp=0xc12681d450 pc=0x1fef8ca
github.com/ipfs/go-ipfs-cmds.(*Command).call(0xc11a4d95c8, 0xc09f06e2a0, {0x2b56388, 0xc09f06e310}, {0x2395140, 0xc0264a7c70})
        /home/luke/gocode/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.8.1/command.go:189 +0x1ac fp=0xc12681d5a0 sp=0xc12681d4e0 pc=0x16fff2c
github.com/ipfs/go-ipfs-cmds.(*Command).Call(0xc0264a7c70, 0x2b5fbf8, {0x2b56388, 0xc09f06e310}, {0x2395140, 0xc0264a7c70})
        /home/luke/gocode/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.8.1/command.go:159 +0x4b fp=0xc12681d640 sp=0xc12681d5a0 pc=0x16ffbcb
github.com/ipfs/go-ipfs-cmds/http.(*handler).ServeHTTP(0xc023c1aae0, {0x2b3aae0, 0xc147df60e0}, 0xc0bb0c9f00)
        /home/luke/gocode/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.8.1/http/handler.go:192 +0xa7e fp=0xc12681d8e8 sp=0xc12681d640 pc=0x170c2be
github.com/ipfs/go-ipfs-cmds/http.prefixHandler.ServeHTTP({{0x25814a1, 0xc166bf59d5}, {0x2b1b300, 0xc023c1aae0}}, {0x2b3aae0, 0xc147df60e0}, 0xc0bb0c9f00)
        /home/luke/gocode/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.8.1/http/apiprefix.go:24 +0x142 fp=0xc12681d950 sp=0xc12681d8e8 pc=0x170a482
github.com/ipfs/go-ipfs-cmds/http.(*prefixHandler).ServeHTTP(0xc023c1ab00, {0x2b3aae0, 0xc147df60e0}, 0xc0bb0c9f00)
        <autogenerated>:1 +0x66 fp=0xc12681d998 sp=0xc12681d950 pc=0x17102a6
github.com/rs/cors.(*Cors).Handler.func1({0x2b3aae0, 0xc147df60e0}, 0xc0bb0c9f00)
        /home/luke/gocode/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1bd fp=0xc12681d9f0 sp=0xc12681d998 pc=0x170805d
net/http.HandlerFunc.ServeHTTP(0x200, {0x2b3aae0, 0xc147df60e0}, 0xc166bf59eb)
        /usr/local/go/src/net/http/server.go:2047 +0x2f fp=0xc12681da18 sp=0xc12681d9f0 pc=0x118cbaf
net/http.(*ServeMux).ServeHTTP(0x7f95801c1ca0, {0x2b3aae0, 0xc147df60e0}, 0xc0bb0c9f00)
        /usr/local/go/src/net/http/server.go:2425 +0x149 fp=0xc12681da68 sp=0xc12681da18 pc=0x118e4a9
github.com/ipfs/go-ipfs/core/corehttp.makeHandler.func1({0x2b3aae0, 0xc147df60e0}, 0x10000c08dc04af0)
        /home/luke/gocode/pkg/mod/github.com/ipfs/go-ipfs@v0.13.1/core/corehttp/corehttp.go:54 +0x6b fp=0xc12681da98 sp=0xc12681da68 pc=0x20741cb
net/http.HandlerFunc.ServeHTTP(0xc166bf59eb, {0x2b3aae0, 0xc147df60e0}, 0xdb2d0e)
        /usr/local/go/src/net/http/server.go:2047 +0x2f fp=0xc12681dac0 sp=0xc12681da98 pc=0x118cbaf
net/http.serverHandler.ServeHTTP({0xc09fd1e7e0}, {0x2b3aae0, 0xc147df60e0}, 0xc0bb0c9f00)
        /usr/local/go/src/net/http/server.go:2879 +0x43b fp=0xc12681db80 sp=0xc12681dac0 pc=0x119011b
net/http.(*conn).serve(0xc14eb8d180, {0x2b55f60, 0xc02d172480})
        /usr/local/go/src/net/http/server.go:1930 +0xb08 fp=0xc12681dfb8 sp=0xc12681db80 pc=0x118bc88
net/http.(*Server).Serve·dwrap·87()
        /usr/local/go/src/net/http/server.go:3034 +0x2e fp=0xc12681dfe0 sp=0xc12681dfb8 pc=0x1190a6e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc12681dfe8 sp=0xc12681dfe0 pc=0xdb4ee1
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8
```

**Comment by enricorotundo** [comment]
How to reproduce this? 🤔

**Comment by lukemarsden** [comment]
make devstack-250
Run benchmark
Only happened to me once though
